# basic options
title: Web Development Blog
author: diana wallace
email: dianawallacedeveloper@gmail.com
description: web development jekyll-blog
twitter_username: dianajwallace
github_username:  dianawallace

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
